### ISSUE TITLE
feat: Adding a Camera to the Screen

### ISSUE THREAD

**Issue by Juhwa-Lee1023** [Juhwa-Lee1023/SolDoKu#1]
## 🎯 Issue Overview
| Issue Contents | MainPage UI 구현 -> Design Asset 변경 |
| --- | --- |
| Deadline date | 2022.09.06 |

## 🏹 Todo
 - [x] Add a view to float the camera on the storyboard.
 - [x] Add camera permission to the info.
 - [x] Add code to display camera on image
