### ISSUE TITLE
feat: Applying the model to a project

### ISSUE THREAD

**Issue by Juhwa-Lee1023** [Juhwa-Lee1023/SolDoKu#15]
## 🎯 Issue Overview
| Issue Contents | Applying the model to a project |
| --- | --- |
| Deadline date | 2022.09.13 |

## 🏹 Todo
 - [x] 숫자 인식 시키기
 - [x] 인식 시킨 숫자를 스도쿠 풀이 알고리즘에 넣기
 - [x] 풀이한 숫자들을 스도쿠에 그리기
