### ISSUE TITLE
bug: There's a bug where the output screen turns 90 degrees, Screen has different left and right spacing

### ISSUE THREAD

**Issue by Juhwa-Lee1023** [Juhwa-Lee1023/SolDoKu#19]
## 🎯 Issue Overview
| Issue Contents |  There's a bug where the output screen turns 90 degrees, Screen has different left and right spacing |
| --- | --- |
| Deadline date | 2022.09.16 |

## 🏹 Todo
 - [x] 실시간 촬영 화면 버그 수정
 - [x] 좌우 패딩값이 다른 버그 수정

<img width="240" alt="image" src="https://user-images.githubusercontent.com/63584245/190406590-c3e2482c-bb5a-40f0-833e-2f64b3a8ffec.jpeg">

 - [x] 카메라에서 불러오는 화면 버그 수정
<img width="240" alt="image" src="https://user-images.githubusercontent.com/63584245/190406611-b8cbd6c9-9fe8-4ab0-b46d-1b7aa43a9c50.jpg">
