### ISSUE TITLE
feat: Sudoku input function

### ISSUE THREAD

**Issue by Juhwa-Lee1023** [Juhwa-Lee1023/SolDoKu#27]
## 🎯 Issue Overview
| Issue Contents |  Sudoku input function |
| --- | --- |
| Deadline date | 2022.09.28 |

## 🏹 Todo
 - [x] 컬렉션 뷰 추가
 - [x] 컬렉션뷰와 스도쿠 배열 연결
 - [x] 컬렉션 뷰를 클릭하여 스도쿠를 입력가능하도록 변경
 - [x] 스도쿠 풀이 알고리즘과 연동
